# Generated by Django 5.1.7 on 2025-03-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_alter_restaurant_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='restaurant',
            table='tourism.restaurant',
        ),
    ]
