# Generated by Django 5.1.7 on 2025-03-19 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0005_restaurant'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='restaurant',
            table='restaurant',
        ),
    ]
