# Generated by Django 5.1.7 on 2025-03-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0007_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchaeologicalSite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('period', models.CharField(blank=True, max_length=100, null=True)),
                ('site_type', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'archaeological_sites',
                'managed': False,
            },
        ),
    ]
